apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iifl-batch-job
resources:
  - namespace.yaml
  - configmaps.yaml
  - secrets.yaml
  - pvc.yaml
  - agent-executor.yaml
  - services.yaml
  - vpa.yaml
