apiVersion: v1
kind: ServiceAccount
metadata:
  name: npa-evals-agent-executor
  namespace: npa-evals
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::598515435126:role/irsa-v2t-backend-bedrock
